// Service worker: makes the app open instantly from cache, even while the Render
// instance is still waking up.
//
// Bump VERSION whenever any shell file changes. The cache name is derived from it,
// so a new version installs a fresh cache and activate() deletes the old ones. The
// ?v= on css and the entry module must match the same number.
const VERSION = '32';
const SHELL = `shell-v${VERSION}`;      // html, css, js, icons — replaced on every release
const MEDIA = 'media-v1';               // exercise images — survives releases, keyed by filename
const API   = 'api-v1';                 // the last good /api/state, for a cold open

// Everything needed to render the app with no network at all. The js list is the
// whole module graph: a missing entry would mean a blank screen offline, because
// one failed import takes the rest down with it.
const SHELL_FILES = [
  '/', '/index.html',
  '/css/tokens.css?v=' + VERSION,
  '/css/app.css?v=' + VERSION,
  '/js/main.js',                      // must match index.html exactly: a query makes a second module
  '/js/state.js', '/js/storage-sync.js', '/js/ui.js', '/js/schedule.js', '/js/today.js',
  '/js/workout.js', '/js/coach.js', '/js/progress.js', '/js/quiz.js', '/js/figures.js',
  '/js/notifications.js', '/js/health.js', '/js/lawbank.js', '/js/matchplan.js', '/js/pitch.js', '/js/mobile.js',
  '/manifest.webmanifest', '/icon-192.png', '/icon-180.png',
  // The font stylesheet is precached; the woff2 files it names are cached on first
  // use instead, because their URLs are generated by Google and change over time.
  'https://fonts.googleapis.com/css2?family=IBM+Plex+Sans+Arabic:wght@400;500;600;700&family=Noto+Kufi+Arabic:wght@600;700;800&display=swap'
];

const isMedia = u => /\/img-[\w-]+\.(?:webp|jpg|png)$/.test(u.pathname);
const isShell = u => u.origin === location.origin &&
  (u.pathname === '/' || u.pathname.startsWith('/css/') || u.pathname.startsWith('/js/') ||
   u.pathname.endsWith('.webmanifest') || /^\/(?:icon|maskable)-/.test(u.pathname));

self.addEventListener('install', e => {
  e.waitUntil((async () => {
    const c = await caches.open(SHELL);
    // one at a time: addAll() rejects the whole batch if any single request fails,
    // and a third-party font URL is exactly the kind of thing that fails
    await Promise.all(SHELL_FILES.map(f => c.add(new Request(f, {cache:'reload'})).catch(() => {})));
    self.skipWaiting();
  })());
});

self.addEventListener('activate', e => {
  e.waitUntil((async () => {
    const keep = new Set([SHELL, MEDIA, API]);
    for (const k of await caches.keys()) if (!keep.has(k)) await caches.delete(k);
    await self.clients.claim();
  })());
});

// The app tells us which illustration style it is set to, and only that style gets
// precached. The other one is never downloaded until the user switches, at which
// point the runtime handler below caches it on the way past.
self.addEventListener('message', e => {
  const d = e.data || {};
  if (d.type === 'precache-style' && Array.isArray(d.urls)){
    e.waitUntil(caches.open(MEDIA).then(c =>
      Promise.all(d.urls.map(async u => {
        if (await c.match(u)) return;                 // already there, do not refetch
        await c.add(new Request(u)).catch(() => {});
      }))
    ));
  }
});

async function networkFirst(req, cacheName){
  const c = await caches.open(cacheName);
  try {
    const r = await fetch(req);
    if (r && r.ok) c.put(req, r.clone());
    return r;
  } catch (e) {
    const hit = await c.match(req);
    if (hit) return hit;
    throw e;
  }
}

async function cacheFirst(req, cacheName){
  const c = await caches.open(cacheName);
  const hit = await c.match(req);
  if (hit) return hit;
  const r = await fetch(req);
  if (r && (r.ok || r.type === 'opaque')) c.put(req, r.clone());
  return r;
}

self.addEventListener('fetch', e => {
  const req = e.request;
  if (req.method !== 'GET') return;
  const u = new URL(req.url);

  // The state row is the one API call worth caching: with a copy of it the app can
  // open fully populated while the server is still waking up. Network first, so a
  // live answer always wins; the cache is only a floor.
  if (u.origin === location.origin && u.pathname === '/api/state'){
    e.respondWith(networkFirst(req, API));
    return;
  }
  // nothing else under /api/ is cacheable: it either mutates or is per-moment
  if (u.origin === location.origin && u.pathname.startsWith('/api/')) return;

  // Navigations come from the cache first so a sleeping server cannot delay the
  // first paint, then the copy is refreshed in the background for next time.
  if (req.mode === 'navigate' || (u.origin === location.origin && u.pathname === '/')){
    e.respondWith((async () => {
      const c = await caches.open(SHELL);
      const hit = await c.match('/index.html') || await c.match('/');
      if (hit){
        e.waitUntil(fetch(req).then(r => { if (r && r.ok) c.put('/index.html', r.clone()); }).catch(() => {}));
        return hit;
      }
      return networkFirst(req, SHELL);
    })());
    return;
  }

  if (isMedia(u)){ e.respondWith(cacheFirst(req, MEDIA)); return; }
  if (isShell(u)){ e.respondWith(cacheFirst(req, SHELL)); return; }
  if (u.hostname.includes('fonts.g')){ e.respondWith(cacheFirst(req, SHELL)); return; }
  // everything else (the weather API) goes straight to the network
});

// reminders pushed from the server
self.addEventListener('push', e => {
  let d = {};
  try { d = e.data ? e.data.json() : {}; } catch (err) { d = { body: e.data ? e.data.text() : '' }; }
  e.waitUntil(self.registration.showNotification(d.title || 'جدول الحكم', {
    body: d.body || '',
    icon: '/icon-192.png',
    badge: '/icon-192.png',
    tag: d.tag || 'coach',
    lang: 'ar',
    dir: 'rtl',
    data: { url: d.url || '/' }
  }));
});
// tapping one opens the app on the right tab instead of a second copy
self.addEventListener('notificationclick', e => {
  e.notification.close();
  const target = (e.notification.data && e.notification.data.url) || '/';
  e.waitUntil(clients.matchAll({ type: 'window', includeUncontrolled: true }).then(list => {
    for (const c of list) if (c.url.startsWith(self.location.origin) && 'focus' in c) { c.navigate(target); return c.focus(); }
    return clients.openWindow(target);
  }));
});
