#!/usr/bin/env python3
"""Copy the question bank from the law app into this one.

The law app (github.com/saud-ux/other-refereea) owns the 350 questions in
questions.py. This app keeps its own copy in js/lawbank.js so the daily
question and the mock exam work offline and do not depend on a second server
being awake. Re-run this whenever the bank changes there:

    git clone --depth 1 https://github.com/saud-ux/other-refereea /tmp/law
    python3 scripts/export-law-bank.py /tmp/law

Question ids (L1-01, ...) come straight from the law app and are what this
app's quiz progress is keyed by, so they must never be renumbered.
"""
import json, os, subprocess, sys

src = sys.argv[1] if len(sys.argv) > 1 else '../other-refereea'
sys.path.insert(0, src)
import questions as Q  # noqa: E402

# The app shows Western digits everywhere (ARCHITECTURE.md §11).
LATIN = {**{chr(0x660 + i): str(i) for i in range(10)}, '٫': '.', '٪': '%'}
def latin(s): return ''.join(LATIN.get(c, c) for c in s) if isinstance(s, str) else s

try:
    commit = subprocess.check_output(['git', '-C', src, 'rev-parse', '--short', 'HEAD'], text=True).strip()
except Exception:
    commit = 'unknown'

cats = {str(n): latin(Q.LAW_TITLES[n]) for n in Q.LAWS}
bank = [{
    'id': x['id'], 'c': str(x['law']), 't': latin(x['topic']), 'y': x['type'], 'd': x['diff'],
    'q': latin(x['q']), 'o': [latin(o) for o in x['options']], 'a': x['a'],
    'w': latin(x['exp']), 'r': latin(x['ref']), 'p': x['page'],
} for x in Q.QUESTIONS]

ids = [x['id'] for x in bank]
assert len(ids) == len(set(ids)), 'duplicate question ids in the source bank'
assert all(0 <= x['a'] < len(x['o']) for x in bank), 'an answer index is out of range'

out = os.path.join(os.path.dirname(os.path.abspath(__file__)), '..', 'js', 'lawbank.js')
with open(out, 'w', encoding='utf-8') as f:
    f.write('// lawbank.js — GENERATED by scripts/export-law-bank.py. Do not edit by hand.\n')
    f.write(f'// Source: github.com/saud-ux/other-refereea questions.py @ {commit}, {len(bank)} questions.\n')
    f.write('// Fields: id, c law number, t topic, y type (mcq|tf|scenario), d difficulty 1-3,\n')
    f.write('//         q question, o options, a answer index, w explanation, r reference, p page.\n')
    f.write(f'export const LAW_SOURCE = {json.dumps({"commit": commit, "count": len(bank)})};\n')
    f.write(f'export const LAW_CATS = {json.dumps(cats, ensure_ascii=False)};\n')
    f.write('export const LAW_BANK = [\n')
    f.write(',\n'.join(json.dumps(x, ensure_ascii=False, separators=(',', ':')) for x in bank))
    f.write('\n];\n')
print(f'wrote {len(bank)} questions from {commit} to js/lawbank.js')
